from dataclasses import dataclass
from datetime import datetime
from typing import Optional, Literal


class Event:
    """Base class for all events in the system."""

    pass


@dataclass
class MarketEvent(Event):
    """
    Triggered when new market data (bars/ticks) is available.
    Processing this event updates the portfolio state and may trigger strategy signals.
    """

    timestamp: datetime
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    type: str = "MARKET"


@dataclass
class SignalEvent(Event):
    """
    generated by a Strategy/Agent, indicating a desire to trade.
    """

    timestamp: datetime
    symbol: str
    direction: Literal["LONG", "SHORT", "EXIT"]
    strength: float = 1.0  # 0.0 to 1.0, could map to position sizing
    type: str = "SIGNAL"


@dataclass
class OrderEvent(Event):
    """
    A request to execute a trade, sent from Portfolio/Risk to ExecutionHandler.
    """

    timestamp: datetime
    symbol: str
    order_type: Literal["MARKET", "LIMIT", "STOP"]
    quantity: int
    direction: Literal["BUY", "SELL"]
    type: str = "ORDER"


@dataclass
class FillEvent(Event):
    """
    Represents the actual execution of an order (simulated or real).
    """

    timestamp: datetime
    symbol: str
    exchange: str
    quantity: int
    direction: Literal["BUY", "SELL"]
    fill_cost: float  # Price * Quantity, or just Price? Usually per-share price * qty, or total cost.
    commission: float
    price: float  # The price at which it was filled
    type: str = "FILL"
