from typing import TypedDict, Annotated, List, Dict, Any, Optional
from operator import add


class AgentState(TypedDict):
    """
    Shared state for the Cognitive Engine.
    Acts as the 'Context Window' for the graph.
    """

    # Chat History (Standard LangChain format)
    messages: Annotated[List[Dict[str, Any]], add]

    # Market Data Context (Raw data fetched by tools)
    market_data: Dict[str, Any]

    # Reasoning Trace (Chain of Thought logs from agents)
    reasoning_trace: Annotated[List[str], add]

    # Current Market Regime (Set by Macro Agent)
    market_regime: str

    # Target Sectors (Set by Macro Agent)
    target_sectors: List[str]

    # Candidate Trades (Proposed by Analyst Agent)
    candidate_trades: List[Dict[str, Any]]

    # Final Orders (Generated by Execution Agent)
    final_orders: List[Dict[str, Any]]

    # Routing Key (Determines next node)
    next_step: str
