from typing import TypedDict, Annotated, List, Dict, Any, Optional
from operator import add
from enum import Enum


class TradingStatus(str, Enum):
    ON = "ON"
    OFF = "OFF"
    PAUSED = "PAUSED"
    ACTIVE = "ACTIVE"
    HALTED_PHYSICS = "HALTED_PHYSICS"
    HALTED_RISK = "HALTED_RISK"
    HALTED_DRAWDOWN = "HALTED_DRAWDOWN"
    SLEEPING = "SLEEPING"


class AgentState(TypedDict, total=False):
    """
    Shared state for the Cognitive Engine.
    Acts as the 'Context Window' for the graph.
    """

    # Chat History (Standard LangChain format)
    messages: Annotated[List[Dict[str, Any]], add]

    # Market Data Context (Raw data fetched by tools)
    market_data: Dict[str, Any]

    # Reasoning Trace (Chain of Thought logs from agents)
    reasoning_trace: Annotated[List[str], add]

    # Current Market Regime (Set by Macro Agent)
    market_regime: str
    regime: str  # Alias or related to market_regime
    alpha: float  # Power Law Alpha

    # Target Sectors (Set by Macro Agent)
    target_sectors: List[str]

    # Candidate Trades (Proposed by Analyst Agent)
    candidate_trades: List[Dict[str, Any]]

    # Final Orders (Generated by Execution Agent)
    final_orders: List[Dict[str, Any]]

    # System Status & Accounting
    status: str  # TradingStatus
    nav: float
    cash: float
    daily_pnl: float
    max_drawdown: float
    risk_score: float
    current_alpha: float
    trade_decision: str  # E.g. "approved", "rejected"

    # Routing Key (Determines next node)
    next_step: str
