"""initial_schema

Revision ID: 3c7359378933
Revises: 
Create Date: 2025-12-16 18:36:03.012238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c7359378933'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('macro_ticks', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('macro_ticks', 'symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('macro_ticks', 'regime_tag',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('macro_ticks_time_idx'), table_name='macro_ticks')
    op.drop_index(op.f('idx_macro_ticks_symbol_time'), table_name='macro_ticks')
    op.create_index('idx_macro_ticks_symbol_time', 'macro_ticks', ['symbol', 'time'], unique=False, schema='public')
    op.alter_column('market_ticks', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('market_ticks', 'symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('market_ticks_time_idx'), table_name='market_ticks')
    op.drop_index(op.f('idx_market_ticks_symbol_time'), table_name='market_ticks')
    op.create_index('idx_market_ticks_symbol_time', 'market_ticks', ['symbol', 'time'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_market_ticks_symbol_time', table_name='market_ticks', schema='public')
    op.create_index(op.f('idx_market_ticks_symbol_time'), 'market_ticks', ['symbol', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('market_ticks_time_idx'), 'market_ticks', [sa.literal_column('time DESC')], unique=False)
    op.alter_column('market_ticks', 'symbol',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('market_ticks', 'time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_macro_ticks_symbol_time', table_name='macro_ticks', schema='public')
    op.create_index(op.f('idx_macro_ticks_symbol_time'), 'macro_ticks', ['symbol', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('macro_ticks_time_idx'), 'macro_ticks', [sa.literal_column('time DESC')], unique=False)
    op.alter_column('macro_ticks', 'regime_tag',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('macro_ticks', 'symbol',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('macro_ticks', 'time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
