"""add_vectors

Revision ID: cf5d61bc6976
Revises: 3c7359378933
Create Date: 2025-12-16 18:44:15.163233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = "cf5d61bc6976"
down_revision: Union[str, Sequence[str], None] = "3c7359378933"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "market_state_embeddings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        "idx_market_embeddings_hnsw",
        "market_state_embeddings",
        ["embedding"],
        unique=False,
        schema="public",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "idx_market_embeddings_symbol_time",
        "market_state_embeddings",
        ["symbol", "timestamp"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_market_embeddings_symbol_time",
        table_name="market_state_embeddings",
        schema="public",
    )
    op.drop_index(
        "idx_market_embeddings_hnsw",
        table_name="market_state_embeddings",
        schema="public",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("market_state_embeddings", schema="public")
    # ### end Alembic commands ###
