"""
Business Metrics Module for Curiosity Cottage Trading System.

This module defines OpenTelemetry metrics for trading operations,
physics calculations, and LLM signals to provide business-level observability.
"""

from opentelemetry import metrics
from opentelemetry import trace
import logging

logger = logging.getLogger(__name__)

# Get meter for creating metrics
meter = metrics.get_meter(__name__, version="2.0")

# ============================================================================
# TRADING METRICS
# ============================================================================

trades_total = meter.create_counter(
    name="cc.trades.total", description="Total number of trades executed", unit="1"
)

trade_value = meter.create_histogram(
    name="cc.trades.value", description="Dollar value of trades", unit="USD"
)

trade_latency = meter.create_histogram(
    name="cc.trades.latency", description="Time from signal to execution", unit="ms"
)

execution_slippage = meter.create_histogram(
    name="cc.execution.slippage", description="Slippage buffer percentage", unit="1"
)

# ============================================================================
# ANALYST METRICS
# ============================================================================

analyst_latency = meter.create_histogram(
    name="cc.analyst.latency", description="Time taken for analysis loop", unit="ms"
)

candidate_count = meter.create_histogram(
    name="cc.analyst.candidates", description="Number of candidates found", unit="1"
)

# ============================================================================
# SIGNAL METRICS
# ============================================================================

signals_total = meter.create_counter(
    name="cc.signals.total", description="Total signals generated by LLM", unit="1"
)

signal_confidence = meter.create_histogram(
    name="cc.signals.confidence",
    description="LLM signal confidence distribution",
    unit="1",
)

signal_changes = meter.create_counter(
    name="cc.signals.changes",
    description="Number of times signal changed direction",
    unit="1",
)

# ============================================================================
# PHYSICS METRICS
# ============================================================================

hurst_exponent = meter.create_gauge(
    name="cc.physics.hurst", description="Current Hurst exponent value (fractal memory)"
)

alpha_tail = meter.create_gauge(
    name="cc.physics.alpha", description="Heavy tail alpha (Hill Estimator)"
)

velocity = meter.create_gauge(
    name="cc.physics.velocity", description="Kalman filter velocity estimate"
)

acceleration = meter.create_gauge(
    name="cc.physics.acceleration", description="Kalman filter acceleration estimate"
)

regime_duration = meter.create_histogram(
    name="cc.physics.regime_duration",
    description="Duration spent in each regime",
    unit="s",
)

# ============================================================================
# LLM METRICS
# ============================================================================

llm_inference_time = meter.create_histogram(
    name="cc.llm.inference_time", description="LLM inference latency", unit="ms"
)

llm_tokens = meter.create_histogram(
    name="cc.llm.tokens", description="Number of tokens in LLM response", unit="1"
)

llm_errors = meter.create_counter(
    name="cc.llm.errors", description="LLM inference errors", unit="1"
)

# ============================================================================
# MARKET METRICS
# ============================================================================

market_price = meter.create_gauge(
    name="cc.market.price", description="Current market price"
)

market_spread = meter.create_histogram(
    name="cc.market.spread", description="Bid-ask spread", unit="USD"
)

data_staleness = meter.create_histogram(
    name="cc.market.staleness", description="Age of market data", unit="ms"
)

# ============================================================================
# RISK METRICS
# ============================================================================

position_size = meter.create_gauge(
    name="cc.risk.position_size", description="Current position size"
)

risk_multiplier = meter.create_histogram(
    name="cc.risk.multiplier",
    description="Risk multiplier (lambda) based on alpha",
    unit="1",
)

vetoes_total = meter.create_counter(
    name="cc.risk.vetoes",
    description="Number of trades vetoed by risk management",
    unit="1",
)

# ============================================================================
# STRATEGY METRICS
# ============================================================================

strategy_mode_duration = meter.create_histogram(
    name="cc.strategy.mode_duration",
    description="Duration in each strategy mode (TREND/REVERSION)",
    unit="s",
)

# ============================================================================
# MEMORY METRICS
# ============================================================================

memory_operations = meter.create_counter(
    name="cc.memory.operations", description="Vector DB operations", unit="1"
)

# ============================================================================
# FORECASTING METRICS (Chronos-Bolt + RAF)
# ============================================================================

forecast_uncertainty = meter.create_histogram(
    name="cc.forecast.uncertainty",
    description="Spread between P90 and P10 forecasts",
    unit="1",
)

forecast_trend = meter.create_gauge(
    name="cc.forecast.trend",
    description="Predicted trend percentage (Chronos P50)",
)

raf_similarity = meter.create_histogram(
    name="cc.raf.similarity",
    description="Similarity score of retrieved market analogs",
    unit="1",
)

raf_outcome = meter.create_gauge(
    name="cc.raf.outcome",
    description="Weighted forward return outcome from RAF",
)

# ============================================================================
# BACKTEST METRICS (The Quantum Holodeck)
# ============================================================================

backtest_sharpe = meter.create_gauge(
    name="cc.backtest.sharpe",
    description="Last backtest Sharpe Ratio",
)

backtest_drawdown = meter.create_gauge(
    name="cc.backtest.drawdown",
    description="Last backtest Max Drawdown",
)

backtest_return = meter.create_gauge(
    name="cc.backtest.return",
    description="Last backtest Total Return",
)

# ============================================================================
# HELPER FUNCTIONS WITH EXEMPLARS
# ============================================================================


def record_histogram_with_exemplar(histogram, value: float, attributes: dict):
    """
    Record a histogram value with an exemplar linking to current trace.

    This creates a link from the metric to the trace in Grafana,
    allowing you to navigate from metrics → traces.
    """
    span = trace.get_current_span()
    span_context = span.get_span_context()

    if span_context.is_valid:
        # Create exemplar with trace context
        # exemplar = {
        #     "trace_id": format(span_context.trace_id, "032x"),
        #     "span_id": format(span_context.span_id, "016x"),
        # }

        # Record with exemplar (note: exemplar support varies by backend)
        # For now, just record normally - exemplar encoding happens in SDK
        histogram.record(value, attributes=attributes)
    else:
        # No active trace, record without exemplar
        histogram.record(value, attributes=attributes)


def get_trace_context():
    """Get current trace context for logging."""
    span = trace.get_current_span()
    ctx = span.get_span_context()

    if ctx.is_valid:
        return {
            "trace_id": format(ctx.trace_id, "032x"),
            "span_id": format(ctx.span_id, "016x"),
        }
    return {"trace_id": "0" * 32, "span_id": "0" * 16}
